// Include headers in all files to support Atom's Asciidoc Preview plugin.
include::../header.adoc[]

:git-book: https://git-scm.com/book
:github-flow: https://guides.github.com/introduction/flow/

=== Git
We use Git as a version control system. Our repositories are hosted on
https://github.com[GitHub^]. {git-book}[This book^] is a great Git tutorial,
read it.

We use {github-flow}[GitHub flow^] as our primary git workflow. Get familiar
with it.

Learn why https://chris.beams.io/posts/git-commit/[readable commit messages
matter^]. And start using `git blame` daily.

Learn about `git add --patch`, `git reset`, and `git commit --amend`.

Become friends with `git rebase -i` and never merge _master_ into
your feature branch again.

[TIP]
===============================
In case you have your personal email set up in the global git config (`git config --global --list`), you can override it by including config file based on the current git directory.

global config `~/.gitconfig`
```
[user]
     name = Joe Srna
     email = joe.srna@gmail.com
[includeIf "gitdir:~/Projects/vacuumlabs/"]
    path = ~/Projects/vacuumlabs/.gitconfig
```

work related config `~/Projects/vacuumlabs/.gitconfig`
```
[user]
     email = joe.srna@vacuumlabs.com
```

You can verify the change by running `git config --list` within different directories. Keep in mind, that this will work correctly only in directories containing a git repository. For more information about conditional includes, visit https://git-scm.com/docs/git-config#_conditional_includes[official documentation^].
===============================
