// Include headers in all files to support Atom's Asciidoc Preview plugin.
include::../header.adoc[]

:git-book: https://git-scm.com/book
:github-flow: https://guides.github.com/introduction/flow/
:ssh-key: https://help.github.com/articles/checking-for-existing-ssh-keys/
:generate-ssh-key: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key
:github-ssh-key: https://github.com/settings/keys
:google-doc-ssh-key: https://docs.google.com/a/vacuumlabs.com/spreadsheets/d/144yVJFm1VIqRIBtcLNUAR8GNlhsBSPOtHiqA_ovF0zI/edit?usp=sharing
:gpg-key: https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/generating-a-new-gpg-key
:gpg-signing: https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits

=== Git
We use Git as a version control system. Our repositories are hosted on
https://github.com[GitHub^]. {git-book}[This book^] is a great Git tutorial,
read it.

We use {github-flow}[GitHub flow^] as our primary git workflow. Get familiar
with it.

Learn why https://chris.beams.io/posts/git-commit/[readable commit messages
matter^]. And start using `git blame` daily.

Learn about `git add --patch`, `git reset`, and `git commit --amend`.

Become friends with `git rebase -i` and never merge _master_ into
your feature branch again.

[TIP]
===============================
In case you have your personal email set up in the global git config (`git config --global --list`), you can override it by including config file based on the current git directory.

global config `~/.gitconfig`
```
[user]
     name = Joe Srna
     email = joe.srna@gmail.com
[includeIf "gitdir:~/Projects/vacuumlabs/"]
    path = ~/Projects/vacuumlabs/.gitconfig
```

work related config `~/Projects/vacuumlabs/.gitconfig`
```
[user]
     email = joe.srna@vacuumlabs.com
```

You can verify the change by running `git config --list` within different directories.
===============================

==== Credentials
For full access to our projects {ssh-key}[SSH key^] will be required. Add your public key to {github-ssh-key}[Github keys^] and to our {google-doc-ssh-key}[internal Google Doc^]. If you don't have one, you will need to {generate-ssh-key}[generate it^].

[TIP]
===============================
If you've set up SSH keys on your personal computer before onboarding, you will need to generate a new key, or copy contents `~/.ssh` folder from your personal to your work laptop.
===============================

It is also useful to {gpg-key}[generate GPG key^]. This will result in better security, a more professional look, and a [green]*Verified* badge that some open-source projects require. After generating you will also need to add this key to {github-ssh-key}[Github keys^] and enable {gpg-signing}[GPG signing^].